### ISSUE TITLE
When is `builder.config.js` executed?

### ISSUE THREAD

**Issue by j0214ack** [BuilderIO/blog-example#1]
Hello BuilderIO team:

I am looking for the best place to call `Builder.registerComponent`. And I came across this repo and saw `builder.config.js`

However, I still don't understand when `builder.config.js` run.

We have an ui-kit library in our team and if I want to register all components in the library, where is the place to call `builder.registerComponent`?

**Comment by steve8708** [comment]
hey @j0214ack ! so that file name is purely a convention some use, it has no special behavior. in this example it's being imported [here](https://github.com/BuilderIO/blog-example/blob/030404372dbaba9051b4349922ce641cb614ea87/pages/blog/%5B...slug%5D.js#L3) so that the registered components are available on that page for use in the `<BuilderComponent>` [down below](https://github.com/BuilderIO/blog-example/blob/030404372dbaba9051b4349922ce641cb614ea87/pages/blog/%5B...slug%5D.js#L36)
